AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: test-502
      Policies:
        - PolicyName: AmazonS3ReadOnlyAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: '*'
